### ISSUE TITLE
Discount on Sales

### ISSUE THREAD

**Issue by whoami1904** [opensourcepos/opensourcepos#2061]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.3
- OSPOS git commit hash is: 
- PHP version is: 5.7
- MySQL or MariaDB version is: 5.7
- OS and version is: ubuntu server 16.04
- WebServer is: 
- Selected language is: En
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

- I want to discount money instead of percent(%). How can i do that? My mean is not delete Disc%, so i want to add one more column beside Disc%.
![money](https://user-images.githubusercontent.com/39585711/43067272-17307480-8e91-11e8-9e81-1e010fb37b3b.JPG)

**Comment by daN4cat** [comment]
This was requested in the past, please search open and closed issues.

**Comment by erastus91** [comment]
I did it my way, I do not know if it's the right solution but it works for me

![discount-mount](https://user-images.githubusercontent.com/6712397/43084325-15175390-8e5e-11e8-9028-dec569c77a3a.png)
![discount-percent](https://user-images.githubusercontent.com/6712397/43084342-1bd15532-8e5e-11e8-8878-028295f56634.png)

**Comment by mckaygerhard** [comment]
show some piece of code to property help

**Comment by mckaygerhard** [comment]
@erastus91  i think from proint of view of user it's better as show in those pictures, show some piece of code to property help

**Comment by whoami1904** [comment]
@erastus91 How can you did it, pls show me. Thank a lot!

**Comment by WebShells** [comment]
It is (Y)

**Comment by erastus** [comment]
@mclaos Can you explain what you mean, what use does it have?

**Comment by erastus** [comment]
@whoami1904  Can you verify the commits, is it what you were looking for or something similar?

**Comment by erastus** [comment]
@whoami1904  https://github.com/opensourcepos/opensourcepos/pull/2091

**Comment by mclaos** [comment]
@Erastus in version 3.2.3 the discount is in percentage which is sometime very difficult to make a discount for customer for example if the price is 13 dollars and you want to make 1.5 dollars for discount, and so many time I found very hard to make the discount without ADMIN permission.

**Comment by erastus** [comment]
este commit https://github.com/opensourcepos/opensourcepos/pull/2091

![screenshot_8](https://user-images.githubusercontent.com/6712397/44471380-64b3b380-a5f1-11e8-88c3-686a163c1241.png)
![screenshot_9](https://user-images.githubusercontent.com/6712397/44471384-68473a80-a5f1-11e8-97cf-c4a72748a136.png)
by default the option is in percentage, if you activate the box it is in fixed discount (currency)
![screenshot_10](https://user-images.githubusercontent.com/6712397/44471391-6d0bee80-a5f1-11e8-9684-89d8a5577ea0.png)
you can apply both discounts at the same time, just click to change the discount rate
![screenshot_11](https://user-images.githubusercontent.com/6712397/44471401-6f6e4880-a5f1-11e8-8b22-099711e74691.png)

**Comment by erastus** [comment]
@odiea thanks,

**Comment by mclaos** [comment]
@erastus Does this function be available in the 3.3.3 version? Because I'm now using 3.2.3 version. However, thank you very much for your efforts and works in trying to make OSPOS more user-friendly. I really appreciated.

**Comment by whoami1904** [comment]
@eratus I must be edit every php file as #2091 or Can i download new 
version (3.4.0). May you give me download link. Thank for your support.

*Hang Vinh Nam* | IT Staff | *The Annam Group*
322 Dien Bien Phu, W22, Binh Thanh District, Ho Chi Minh City , Vietnam
T: +848 3512 6400 | F: +848 3512 6401 | M: +84 (0)9 090 70 842
www.annam-group.com <http://www.annam-group.com/>

**Comment by erastus** [comment]
I already made the code pull request. I don't know if they include it. just wait

to try, you can clone my repository
https://github.com/erastus/opensourcepos

**Comment by eratus** [comment]
Hi, looks like you meant to contact erastus, this is eratus. Cheers

**Comment by daN4cat** [comment]
Thank you @erastus for all the good work, just a couple of small changes and it will make it 3.3.0 version.
So in the future you don't need to spend time in merging your code with newer version of OSPOS.

**Comment by daN4cat** [comment]
@erastus I've merged to master and tested but the sale cannot complete and I cannot suspend the sale neither.
Can you please test and fix?

**Comment by erastus** [comment]
Yes, now I'm testing

**Comment by daN4cat** [comment]
Please note that I tested without adding any customer. Just added one item with one discount type selection and then suspended, before adding any payment.

**Comment by erastus** [comment]
I execute the command? $bower update?

**Comment by daN4cat** [comment]
You need to add an item and do not touch the selection item, nor add any customer and then it fails in suspend pre-payment or complete.

If you click the discount item to change then it will work.

**Comment by daN4cat** [comment]
There is probably some default not set.

**Comment by erastus** [comment]
I found the error.

INSERT INTO `ospos_app_config` (`key`, `value`) VALUES
('multi_pack_enabled', '0'),
('default_sales_discount_type', '0');

**Comment by daN4cat** [comment]
what's the fix?

**Comment by erastus** [comment]
('default_sales_discount_type', '0');

**Comment by erastus** [comment]
('default_sales_discount_type', '0');
it is not inserted in the database, because it exists ('multi_pack_enabled', '0'),

therefore, cancel that part of the migration code

**Comment by daN4cat** [comment]
don't get, I can't see the difference...

**Comment by erastus** [comment]
the solution would be 

INSERT INTO `ospos_app_config` (`key`, `value`) VALUES
('multi_pack_enabled', '0');

ALTER TABLE `ospos_items`
  ADD COLUMN `qty_per_pack` decimal(15,3) NOT NULL DEFAULT 1,
  ADD COLUMN `pack_name` varchar(8) DEFAULT 'Each',
  ADD COLUMN `low_sell_item_id` int(10) DEFAULT 0;

UPDATE `ospos_items`
  SET `low_sell_item_id` = `item_id`
  WHERE `low_sell_item_id` = 0;

--
-- Add support for Discount on Sales Fixed
--

INSERT INTO `ospos_app_config` (`key`, `value`) VALUES
('default_sales_discount_type', '0');

ALTER TABLE `ospos_item_kits`
	CHANGE COLUMN `kit_discount_percent` `kit_discount` DECIMAL(15,2) NOT NULL DEFAULT 0 AFTER `item_id`,
	ADD COLUMN `kit_discount_type` TINYINT(2) NOT NULL DEFAULT '0' AFTER `kit_discount`;

ALTER TABLE `ospos_customers`
	CHANGE COLUMN `discount_percent` `discount` DECIMAL(15,2) NOT NULL DEFAULT 0 AFTER `sales_tax_code`,
	ADD COLUMN `discount_type` TINYINT(2) NOT NULL DEFAULT '0' AFTER `discount`;

ALTER TABLE `ospos_sales_items`
	CHANGE COLUMN `discount_percent` `discount` DECIMAL(15,2) NOT NULL DEFAULT 0 AFTER `item_unit_price`,
	ADD COLUMN `discount_type` TINYINT(2) NOT NULL DEFAULT '0' AFTER `discount`;

ALTER TABLE `ospos_receivings_items`
	CHANGE COLUMN `discount_percent` `discount` DECIMAL(15,2) NOT NULL DEFAULT 0 AFTER `item_unit_price`,
	ADD COLUMN `discount_type` TINYINT(2) NOT NULL DEFAULT '0' AFTER `discount`;

**Comment by daN4cat** [comment]
ok, fixed and restart from scratch the docker and see what happens.

**Comment by daN4cat** [comment]
no, it doesn't fix removing just ('default_sales_discount_type', '0');

**Comment by daN4cat** [comment]
no, it doesn't work with your fix.

**Comment by erastus** [comment]
I would add the new fields to the database/table.sql

**Comment by daN4cat** [comment]
it has nothing to do with that.

**Comment by daN4cat** [comment]
are you able to reproduce it?

**Comment by erastus** [comment]
INSERT INTO ospos_app_config( key, value) VALUES 
('default_sales_discount_type', '0');

**Comment by daN4cat** [comment]
please reproduce and fix. I need to unplug now.

**Comment by SteveIreland** [comment]
Agreed my first pass at it works beautifully.  I was able to do a percent discount on one item and a fixed amount discount on the second item and generates a receipt with the correct numbers.

I also love how easy it is to use.  Great job @erastus!  Thank you for this contribution.

**Comment by eratus** [comment]
Can you guys take me off this list, please? I'm not erastus, I'm eratus. I
have nothing to do with this project.

**Comment by SteveIreland** [comment]
Eratus, when you posted on this thread you automatically became a participant.  So I deleted your comments and removed the typo that sent the original email to you so you should not receive this comment.  However, if you do please let me know and we'll take another shot at it.

**Comment by erastus** [comment]
![screenshot_20180903-194745](https://user-images.githubusercontent.com/6712397/45004453-6b0f3b80-afb2-11e8-87e8-a968c059394b.png)

**Comment by daN4cat** [comment]
Sorry guys but I still see the problem. I'll see if I can get to the root cause of this problem.

**Comment by daN4cat** [comment]
That's not required either. Migration script is run the first time and updates the database.

**Comment by daN4cat** [comment]
I spotted the issue related to a copy and paste from yesterday.

BTW, if somebody wants to run phpmyadmin in the docker use this docker-compose.yml:

```
version: '2'

volumes:
    uploads:
        driver: local
  
services:
    sqlscript:
        build:
            context: database/
            dockerfile: Dockerfile
    php:
        build:
            context: .
            dockerfile: Dockerfile
        links:
            - mysql
        ports:
            - "80:80"
        volumes:
            - uploads:/app/public/uploads
        environment:
            - FORCE_HTTPS=false
            - PHP_TIMEZONE=UTC
            - MYSQL_USERNAME=admin
            - MYSQL_PASSWORD=pointofsale
            - MYSQL_DB_NAME=ospos
            - MYSQL_HOST_NAME=mysql

    mysql:
        image: mariadb:10.3.9
        environment:
            - MYSQL_ROOT_PASSWORD=pointofsale
            - MYSQL_DATABASE=ospos
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=pointofsale
        ports:
            - "3306:3306"
        volumes_from:
            - sqlscript

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
           - '8000:80'
        links:
            - mysql:mysql
        environment:
            - MYSQL_USERNAME=admin
            - MYSQL_ROOT_PASSWORD=pointofsale
            - PMA_HOST=mysql
```
