### ISSUE TITLE
docker-compose deployment got: HTTP ERROR 500

### ISSUE THREAD

**Issue by batara666** [opensourcepos/opensourcepos#3352]
source code: branch master (2-hour ago)

docker-compose file:
```yml
version: '3.4'

volumes:
    uploads:
        driver: local
    logs:
        driver: local
    mysql:
        driver: local

networks:
    app_net:
    db_net:

services:
    ospos:
        image: jekkos/opensourcepos:3.3.5
        restart: always
        depends_on:
          - mysql
        ports:
          - "3500:80"
        networks:
          - app_net
          - db_net
        volumes:
          - uploads:/app/public/uploads
          - logs:/app/application/logs
        environment:
          - CI_ENV=development
          - FORCE_HTTPS=false
          - PHP_TIMEZONE=UTC
          - MYSQL_USERNAME=myusername
          - MYSQL_PASSWORD=mypassword
          - MYSQL_DB_NAME=ospos
          - MYSQL_HOST_NAME=mysql

    mysql:
        image: mariadb:10.5
        container_name: mysql
        restart: always
        expose:
          - "3306"
        ports:
          - "3600:3306"
        networks:
          - db_net
        volumes:
          - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql
          - mysql:/var/lib/mysql:rw
        environment:
          - MYSQL_ROOT_PASSWORD=mypassword
          - MYSQL_DATABASE=ospos
          - MYSQL_USER=myusername
          - MYSQL_PASSWORD=mypassword
 ```

docker-compose up log:

```txt
Creating network "opensourcepos_db_net" with the default driver
Creating network "opensourcepos_app_net" with the default driver
Creating mysql ... done
Creating opensourcepos_ospos_1 ... done
Attaching to mysql, opensourcepos_ospos_1
mysql    | 2021-11-04 13:40:49+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.5.12+maria~focal started.
mysql    | 2021-11-04 13:40:49+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql    | 2021-11-04 13:40:49+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.5.12+maria~focal started.
mysql    | 2021-11-04 13:40:49 0 [Note] mysqld (mysqld 10.5.12-MariaDB-1:10.5.12+maria~focal) starting as process 1 ...
mysql    | 2021-11-04 13:40:49 0 [Note] InnoDB: Uses event mutexes
mysql    | 2021-11-04 13:40:49 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mysql    | 2021-11-04 13:40:49 0 [Note] InnoDB: Number of pools: 1
mysql    | 2021-11-04 13:40:49 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
mysql    | 2021-11-04 13:40:49 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
mysql    | 2021-11-04 13:40:49 0 [Note] InnoDB: Using Linux native AIO
mysql    | 2021-11-04 13:40:49 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
mysql    | 2021-11-04 13:40:49 0 [Note] InnoDB: Completed initialization of buffer pool
mysql    | 2021-11-04 13:40:49 0 [Note] InnoDB: Starting crash recovery from checkpoint LSN=47436,47436
mysql    | 2021-11-04 13:40:49 0 [Note] InnoDB: 128 rollback segments are active.
mysql    | 2021-11-04 13:40:49 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
mysql    | 2021-11-04 13:40:49 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mysql    | 2021-11-04 13:40:49 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mysql    | 2021-11-04 13:40:49 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mysql    | 2021-11-04 13:40:49 0 [Note] InnoDB: 10.5.12 started; log sequence number 47448; transaction id 31
mysql    | 2021-11-04 13:40:49 0 [Note] Plugin 'FEEDBACK' is disabled.
mysql    | 2021-11-04 13:40:49 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mysql    | 2021-11-04 13:40:49 0 [Note] InnoDB: Buffer pool(s) load completed at 211104 13:40:49
mysql    | 2021-11-04 13:40:49 0 [Note] Server socket created on IP: '::'.
mysql    | 2021-11-04 13:40:49 0 [Warning] 'proxies_priv' entry '@% root@855c453fcea9' ignored in --skip-name-resolve mode.
mysql    | 2021-11-04 13:40:49 0 [Note] Reading of all Master_info entries succeeded
mysql    | 2021-11-04 13:40:49 0 [Note] Added new Master_info '' to hash table
mysql    | 2021-11-04 13:40:49 0 [Note] mysqld: ready for connections.
mysql    | Version: '10.5.12-MariaDB-1:10.5.12+maria~focal'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
ospos_1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.0.3. Set the 'ServerName' directive globally to suppress this message
ospos_1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.0.3. Set the 'ServerName' directive globally to suppress this message
ospos_1  | [Thu Nov 04 13:40:50.200719 2021] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.48 (Debian) PHP/7.4.22 configured -- resuming normal operations
ospos_1  | [Thu Nov 04 13:40:50.201511 2021] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```

when i try to access the site, it's just erroring (500)
